ARG repository
FROM ${repository}:9.0-devel-ubuntu16.04
LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"

ENV CUDNN_VERSION 7.3.0.29
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
            libcudnn7=$CUDNN_VERSION-1+cuda9.0 \
            libcudnn7-dev=$CUDNN_VERSION-1+cuda9.0 && \
    apt-mark hold libcudnn7 && \
    rm -rf /var/lib/apt/lists/*
RUN apt-get install -y wget
RUN wget https://raw.githubusercontent.com/zylhub/misc/master/ubuntu-sources-list/ubuntu16.04-tsinghua -O /etc/apt/sources.list
RUN apt-get update && apt-get install -y python3 python3-pip
RUN wget https://tuna.moe/oh-my-tuna/oh-my-tuna.py && python3 oh-my-tuna.py
RUN pip3 install torch torchvision

