# Use Caffe2 image as parent image
FROM caffe2/caffe2:snapshot-py2-cuda9.0-cudnn7-ubuntu16.04

RUN mv /usr/local/caffe2 /usr/local/caffe2_build
ENV Caffe2_DIR /usr/local/caffe2_build

ENV PYTHONPATH /usr/local/caffe2_build:${PYTHONPATH}
ENV LD_LIBRARY_PATH /usr/local/caffe2_build/lib:${LD_LIBRARY_PATH}

# add
COPY ./pip.conf /etc/pip.conf

# Clone the Detectron repository
RUN git clone https://gitee.com/zylhub/Detectron.git  /detectron
RUN cd /detectron && git checkout 6c5835862888e784e861824e0ad6ac93dd01d8f5

# Install Python dependencies
#RUN pip install -U pip
RUN pip install -r /detectron/requirements.txt

# Install the COCO API
RUN git clone https://gitee.com/zylhub/cocoapi.git /cocoapi
WORKDIR /cocoapi/PythonAPI
RUN make install

# Go to Detectron root
WORKDIR /detectron

# Set up Python modules
RUN make

# [Optional] Build custom ops
RUN make ops

COPY ./ubuntu16.04-aliyun-sources-list /etc/apt/sources.list
RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen zh_CN.UTF-8
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN.UTF-8
ENV LC_ALL zh_CN.UTF-8
